version: "3"

services:
  consumer:
    build: consumer
    links:
      - rabbitmq

  producer:
    build: producer
    links:
      - rabbitmq

  
  rabbitmq:
    image: "rabbitmq:3.6-management-alpine"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
